=== thbrown/softball-scorer/shared/schema/top-level-client.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "http://softball.app/schemas/top-level-client",
  "title": "Top Level Client",
  "description": "Data that gets sent the the client browser. Excludes private account info (password stuff)",
  "type": "object",
  "required": ["metadata", "players", "optimizations", "teams"],
  "properties": {
    "metadata": {
      "description": "Information about the json document itself",
      "type": "object",
      "required": ["version", "scope"],
      "properties": {
        "version": {
          "type": "integer",
          "description": "The version schema version of the json document"
        },
        "scope": {
          "type": "string",
          "enum": ["client"],
          "description": "Schema for the json used on the browser. Client contains all application data and some account data, but not all account data (password hashes are excluded, for instance)."
        }
      }
    },
    "account": { 
      "allOf": [
        { "$ref": "http://softball.app/schemas/account" },
        { "$ref": "http://softball.app/schemas/account-read-only" }
      ]  
    },
    "players": {
      "description": "List of all players associated with this account",
      "type": "array",
      "items": { "$ref": "http://softball.app/schemas/player" }
    },
    "teams": {
      "description": "List of all teams associated with this account",
      "type": "array",
      "items": { 
        "allOf": [
          { "$ref": "http://softball.app/schemas/team-read-only" },
          { "$ref": "http://softball.app/schemas/team" }
        ]  
       }
    },
    "optimizations": {
      "type": "array",
      "description": "List of all optimizations associated with this account",
      "items": { "$ref": "http://softball.app/schemas/optimization" }
    }
  }
}

=== thbrown/softball-scorer/client/test/mock.json
{
  "account": {
    "optimizers": [1, 0, 2, 4],
    "accountId": "1",
    "email": "robert@jordan.com",
    "emailConfirmed": false,
    "balance": 2000
  },
  "metadata": {
    "version": 2,
    "scope": "client"
  },
  "teams": [
    {
      "id": "4i7WarrEmtZMxJ",
      "name": "Team of the Dragon",
      "games": [
        {
          "id": "1",
          "opponent": "Darkfriends",
          "lineup": [
            "3XcBG4OeaNrgHs",
            "5t7RegcwU6GWQ4",
            "5LubX8hY1J9qbi",
            "1Z1tPWhLnGJ9Gs",
            "55DMxux2F3TvER",
            "2JojDb9S2brbVF",
            "3hw09h7XgjfMK7",
            "4e2viYmTSLfKFv",
            "2iTjqxkl8o92IJ",
            "1ajppp381cecS7"
          ],
          "date": 1562826405,
          "lineupType": 2,
          "scoreThem": 0,
          "scoreUs": 0,
          "plateAppearances": [
            {
              "id": "1pupriMTKbq2Se",
              "playerId": "3XcBG4OeaNrgHs",
              "result": "1B",
              "location": {
                "x": 10944,
                "y": 14745
              }
            },
            {
              "id": "3jLZ4mKJGpdHkZ",
              "playerId": "5t7RegcwU6GWQ4",
              "result": "2B",
              "location": {
                "x": 13565,
                "y": 6946
              }
            },
            {
              "id": "5jgJ5xQmDLalwH",
              "playerId": "5LubX8hY1J9qbi",
              "result": "Out",
              "location": {
                "x": 11009,
                "y": 18480
              }
            },
            {
              "id": "5iZ31SDy3uke8M",
              "playerId": "1Z1tPWhLnGJ9Gs",
              "result": "Out",
              "location": {
                "x": 19922,
                "y": 19332
              }
            },
            {
              "id": "29MmiYYdjdhkFH",
              "playerId": "55DMxux2F3TvER",
              "result": "1B",
              "location": {
                "x": 9240,
                "y": 16711
              }
            },
            {
              "id": "4qegIoeF0JVtXJ",
              "playerId": "2JojDb9S2brbVF",
              "result": "2B",
              "location": {
                "x": 21298,
                "y": 6553
              }
            },
            {
              "id": "1QHrSraPIlhohK",
              "playerId": "3hw09h7XgjfMK7",
              "result": "1B",
              "location": {
                "x": 25033,
                "y": 19529
              }
            },
            {
              "id": "0Yf53oSrRsZmhS",
              "playerId": "4e2viYmTSLfKFv",
              "result": "E",
              "location": {
                "x": 20446,
                "y": 7667
              }
            },
            {
              "id": "2rE5BYIB7vWxGY",
              "playerId": "2iTjqxkl8o92IJ",
              "result": "E",
              "location": {
                "x": 9567,
                "y": 10878
              }
            },
            {
              "id": "4UuyGMABG7tefx",
              "playerId": "1ajppp381cecS7",
              "result": "2B",
              "location": {
                "x": 24771,
                "y": 12058
              }
            },
            {
              "id": "2IHrEOVC4hfUTI",
              "playerId": "3XcBG4OeaNrgHs",
              "result": "1B",
              "location": {
                "x": 8126,
                "y": 13958
              }
            },
            {
              "id": "5ToNmeBQmSti1e",
              "playerId": "5t7RegcwU6GWQ4",
              "result": "HRo",
              "location": {
                "x": 7864,
                "y": 2949
              }
            },
            {
              "id": "23sPXvkAIRlXZe",
              "playerId": "5LubX8hY1J9qbi",
              "result": "Out",
              "location": {
                "x": 8060,
                "y": 15334
              }
            },
            {
              "id": "2RIyFscW4D6gXS",
              "playerId": "1Z1tPWhLnGJ9Gs",
              "result": "Out",
              "location": {
                "x": 21101,
                "y": 14745
              }
            },
            {
              "id": "0uwbFxQ9xnCnKV",
              "playerId": "55DMxux2F3TvER",
              "result": "1B",
              "location": {
                "x": 8912,
                "y": 15924
              }
            },
            {
              "id": "4YAXgcUk3FlzfS",
              "playerId": "2JojDb9S2brbVF",
              "result": "3B",
              "location": {
                "x": 20446,
                "y": 8257
              }
            },
            {
              "id": "5iHx971cKNqExA",
              "playerId": "3hw09h7XgjfMK7",
              "result": "SAC",
              "location": {
                "x": 24247,
                "y": 14351
              }
            },
            {
              "id": "0DeeqoIbunTU5H",
              "playerId": "4e2viYmTSLfKFv",
              "result": "2B",
              "location": {
                "x": 24837,
                "y": 11402
              }
            },
            {
              "id": "3V2jZE3wV0P1o2",
              "playerId": "2iTjqxkl8o92IJ",
              "result": "1B",
              "location": {
                "x": 8978,
                "y": 12779
              }
            },
            {
              "id": "1asNvNz984Ec4f",
              "playerId": "1ajppp381cecS7",
              "result": "1B",
              "location": {
                "x": 7077,
                "y": 13041
              }
            },
            {
              "id": "4XKGISwB7QtwP4",
              "playerId": "3XcBG4OeaNrgHs",
              "result": "1B",
              "location": {
                "x": 8388,
                "y": 15334
              }
            },
            {
              "id": "2wpkjtTNKmHgeY",
              "playerId": "5t7RegcwU6GWQ4",
              "result": "Out",
              "location": {
                "x": 10616,
                "y": 6094
              }
            },
            {
              "id": "3M2zRJuphRxieV",
              "playerId": "5LubX8hY1J9qbi",
              "result": "3B",
              "location": {
                "x": 983,
                "y": 15859
              }
            },
            {
              "id": "4PqM5TtfrzenYh",
              "playerId": "1Z1tPWhLnGJ9Gs",
              "result": "1B",
              "location": {
                "x": 21888,
                "y": 13762
              }
            },
            {
              "id": "4O1fKgSCM7utbU",
              "playerId": "55DMxux2F3TvER",
              "result": "HRo",
              "location": {
                "x": 589,
                "y": 851
              }
            },
            {
              "id": "47Ia8L6kRxL2hK",
              "playerId": "2JojDb9S2brbVF",
              "result": "Out",
              "location": {
                "x": 17694,
                "y": 20512
              }
            },
            {
              "id": "2mVqTjIJCX2Wsr",
              "playerId": "3hw09h7XgjfMK7",
              "result": "Out",
              "location": {
                "x": 23985,
                "y": 12582
              }
            },
            {
              "id": "4gJFTAgNDLVfZP",
              "playerId": "4e2viYmTSLfKFv",
              "result": "Out",
              "location": {
                "x": 17759,
                "y": 21495
              }
            },
            {
              "id": "0EqcVjAsXfzCXP",
              "playerId": "2iTjqxkl8o92IJ",
              "result": "1B",
              "location": {
                "x": 7864,
                "y": 12779
              }
            },
            {
              "id": "39AND6zg8BSTB6",
              "playerId": "1ajppp381cecS7",
              "result": "1B",
              "location": {
                "x": 15466,
                "y": 11665
              }
            },
            {
              "id": "3l0DJtEPHkBITp",
              "playerId": "3XcBG4OeaNrgHs",
              "result": "1B",
              "location": {
                "x": 8650,
                "y": 13958
              }
            },
            {
              "id": "4D3O0HOJbMPT1f",
              "playerId": "5t7RegcwU6GWQ4",
              "result": "HRo",
              "location": {
                "x": 14548,
                "y": 3211
              }
            },
            {
              "id": "3ulZVQNnS5t5pb",
              "playerId": "5LubX8hY1J9qbi",
              "result": "3B",
              "location": {
                "x": 30538,
                "y": 16383
              }
            },
            {
              "id": "1aJ8x6vAGPOp1r",
              "playerId": "1Z1tPWhLnGJ9Gs",
              "result": "Out",
              "location": {
                "x": 20774,
                "y": 17694
              }
            },
            {
              "id": "4dOF5sHUVBIjf8",
              "playerId": "55DMxux2F3TvER",
              "result": "Out",
              "location": {
                "x": 16055,
                "y": 29555
              }
            },
            {
              "id": "4JVeZ6CgdxyN2U",
              "playerId": "2JojDb9S2brbVF",
              "result": "SAC",
              "location": {
                "x": 10026,
                "y": 6487
              }
            },
            {
              "id": "3LKPuPxS95sEtE",
              "playerId": "3hw09h7XgjfMK7",
              "result": "FC",
              "location": {
                "x": 19856,
                "y": 17956
              }
            },
            {
              "id": "4T2WaMrH62z03g",
              "playerId": "4e2viYmTSLfKFv",
              "result": "E",
              "location": {
                "x": 14089,
                "y": 20250
              }
            },
            {
